DROP TABLE IF EXISTS TBL_EMPLOYEES;
 
CREATE TABLE TBL_EMPLOYEES (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  full_name VARCHAR(250),
  email VARCHAR(250),
  contact VARCHAR(250),
  salary VARCHAR(250),
  dept  VARCHAR(250) 
);